---
title: "California_Snowpack"
author: "Andre Dextre"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(janitor)
library(here)
library(kableExtra)
library(readr)
library(ggplot2)
library(modelr)
library(knitr)
library(broom)
library(openintro)
library(stringr)
library(lubridate)

options(scipen = 999) # disable scientific notations
### Setting directories ###
rootdir <- getwd() #root directory
datadir <- file.path(rootdir, "water_year_data") #data directory
setwd(rootdir) #working directory

knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Read in the Water Year  2000 Data
wy_2000 <- read_csv(here( "water_year_data", "Whole_WY_2000.csv" ), na = c("T", "NA", "--")) %>% 
  clean_names() %>% 
  replace(is.na(.), 0) %>%
  select(!remarks)
  
compare_2000 <-  read_csv(here( "water_year_data", "Whole_WY_2000.csv" ))

#Read in the Water Year  2001 Data
wy_2001 <- read_csv(here("water_year_data", "Whole_WY_2001.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  transform(new_snow_cm = as.numeric(new_snow_cm)) %>%
  replace(is.na(.), 0) %>%
  select(!remarks)
#Read in the Water Year  2002 Data
wy_2002 <- read_csv(here("water_year_data", "Whole_WY_2002.csv"), na = c("T", "NA", "--"))%>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2003 Data
wy_2003 <- read_csv(here("water_year_data", "Whole_WY_2003.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0)
#Read in the Water Year  2004 Data
wy_2004 <- read_csv(here("water_year_data", "Whole_WY_2004.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2005 Data
wy_2005 <- read_csv(here("water_year_data", "Whole_WY_2005.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0)
#Read in the Water Year  2006 Data
wy_2006 <- read_csv(here("water_year_data", "Whole_WY_2006.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2007 Data
wy_2007 <- read_csv(here("water_year_data", "Whole_WY_2007.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2008 Data
wy_2008 <- read_csv(here("water_year_data", "Whole_WY_2008.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0)
#Read in the Water Year  2009 Data
wy_2009 <- read_csv(here("water_year_data", "Whole_WY_2009.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2010 Data
wy_2010 <- read_csv(here("water_year_data", "Whole_WY_2010.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2011 Data
wy_2011 <- read_csv(here("water_year_data", "Whole_WY_2011.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2012 Data
wy_2012 <- read_csv(here("water_year_data", "Whole_WY_2012.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2013 Data
wy_2013 <- read_csv(here("water_year_data", "Whole_WY_2013.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2014 Data
wy_2014 <- read_csv(here("water_year_data", "Whole_WY_2014.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2015 Data
wy_2015 <- read_csv(here("water_year_data", "Whole_WY_2015.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2016 Data
wy_2016 <- read_csv(here("water_year_data", "Whole_WY_2016.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0)
#Read in the Water Year  2017 Data
wy_2017 <- read_csv(here("water_year_data", "Whole_WY_2017.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0)
#Read in the Water Year  2018 Data
wy_2018 <- read_csv(here("water_year_data", "Whole_WY_2018.csv"), na = c("T", "NA", "--")) %>%
  clean_names() %>%
  select(!remarks) %>%
  replace(is.na(.), 0) 
#Read in the Water Year  2019 Data
wy_2019 <- read_csv(here("water_year_data", "Whole_WY_2019.csv"), na = c("T", "NA", "--")) %>%
  clean_names()%>%
  select(!remarks) %>%
  replace(is.na(.), 0)

```

```{r}
#Merge water year 2000-2003 data into one
wy_2000_2003 <- list(wy_2000, wy_2001, wy_2002, wy_2003) %>%  
  reduce(full_join)
#Merge water year 2004-2019 data into one
wy_2004_2019 <- list(wy_2004, wy_2005, wy_2006, wy_2007,
                     wy_2008, wy_2009, wy_2010, wy_2011,
                     wy_2012, wy_2013, wy_2014, wy_2015,
                     wy_2016, wy_2017,wy_2018, wy_2019) %>%
  reduce(full_join) %>%
  mutate(date = lubridate::mdy(date))
#Join both merged data frames together
water_year <- full_join(wy_2000_2003, wy_2004_2019) %>%
  rename(total_precip_mm = x24_hour_total_precip_mm,
         Date = date)

```

```{r}
#Isolate snow for average
monthly_snow_avg <- water_year %>%
  mutate(date = floor_date(water_year$Date, "month")) %>%
  group_by(date) %>%
  select(date, 
         new_snow_cm, 
         season_total_snow_cm, 
         snowpack_depth_cm, 
         snow_water_equivalent_cm, 
         percent_of_precip_as_snow) %>%
  summarise(date = mean(date),
            new_snow_cm = mean(new_snow_cm),
            snowpack_depth_cm = mean(snowpack_depth_cm),
            snow_water_equivalent_cm = mean(snow_water_equivalent_cm),
            percent_of_precip_as_snow = mean(percent_of_precip_as_snow))
#Isolate precipitation for average
monthly_precip_avg <- water_year %>%
  mutate(date = floor_date(water_year$Date, "month")) %>%
  group_by(date) %>%
  select(date, 
         total_precip_mm, 
         season_total_precip_mm,
         percent_of_precip_as_rain) %>%
  summarise(date = mean(date),
            daily_precip_mm = mean(total_precip_mm),
            season_total_precip_mm = mean(season_total_precip_mm),
            percent_of_precip_as_rain = mean(percent_of_precip_as_rain))
```

```{r}
#Snow yearly data
yearly_snow_avg <- water_year %>%
  mutate(date = floor_date(water_year$Date, "year")) %>%
  group_by(date) %>%
  select(date, 
         new_snow_cm, 
         season_total_snow_cm, 
         snowpack_depth_cm, 
         snow_water_equivalent_cm, 
         percent_of_precip_as_snow) %>%
  summarise(date = mean(date),
            new_snow_cm = mean(new_snow_cm),
            snowpack_depth_cm = mean(snowpack_depth_cm),
            snow_water_equivalent_cm = mean(snow_water_equivalent_cm),
            percent_of_precip_as_snow = mean(percent_of_precip_as_snow))
#Precipitation yearly average
monthly_precip_avg <- water_year %>%
  mutate(date = floor_date(water_year$Date, "year")) %>%
  group_by(date) %>%
  select(date, 
         total_precip_mm, 
         season_total_precip_mm,
         percent_of_precip_as_rain) %>%
  summarise(date = mean(date),
            daily_precip_mm = mean(total_precip_mm),
            season_total_precip_mm = mean(season_total_precip_mm),
            percent_of_precip_as_rain = mean(percent_of_precip_as_rain))
```

```{r}

```
